// Generated by gencpp from file ass2/Goaltype.msg
// DO NOT EDIT!


#ifndef ASS2_MESSAGE_GOALTYPE_H
#define ASS2_MESSAGE_GOALTYPE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ass2
{
template <class ContainerAllocator>
struct Goaltype_
{
  typedef Goaltype_<ContainerAllocator> Type;

  Goaltype_()
    : type(0)  {
    }
  Goaltype_(const ContainerAllocator& _alloc)
    : type(0)  {
  (void)_alloc;
    }



   typedef int32_t _type_type;
  _type_type type;




  typedef boost::shared_ptr< ::ass2::Goaltype_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ass2::Goaltype_<ContainerAllocator> const> ConstPtr;

}; // struct Goaltype_

typedef ::ass2::Goaltype_<std::allocator<void> > Goaltype;

typedef boost::shared_ptr< ::ass2::Goaltype > GoaltypePtr;
typedef boost::shared_ptr< ::ass2::Goaltype const> GoaltypeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ass2::Goaltype_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ass2::Goaltype_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ass2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'ass2': ['/root/catkin_ws/src/ass2/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ass2::Goaltype_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ass2::Goaltype_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ass2::Goaltype_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ass2::Goaltype_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ass2::Goaltype_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ass2::Goaltype_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ass2::Goaltype_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bda37decd5e3814bcc042f341d2e60a1";
  }

  static const char* value(const ::ass2::Goaltype_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbda37decd5e3814bULL;
  static const uint64_t static_value2 = 0xcc042f341d2e60a1ULL;
};

template<class ContainerAllocator>
struct DataType< ::ass2::Goaltype_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ass2/Goaltype";
  }

  static const char* value(const ::ass2::Goaltype_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ass2::Goaltype_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 type\n\
";
  }

  static const char* value(const ::ass2::Goaltype_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ass2::Goaltype_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Goaltype_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ass2::Goaltype_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ass2::Goaltype_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASS2_MESSAGE_GOALTYPE_H
